/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemgs;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ZaHi
 */
public class Login extends javax.swing.JFrame {

    Connection ConnctDB = null;
    PreparedStatement PstLog = null;
    ResultSet ResSetLog = null;

    public Login() {
        initComponents();
        ConnctDB = Connect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JTextField();
        PassForget = new javax.swing.JLabel();
        Entree = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Passwd = new javax.swing.JPasswordField();
        ContactMe = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.setToolTipText("إسم المستخدم");
        UserName.setBorder(new javax.swing.border.MatteBorder(null));
        UserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserNameMouseClicked(evt);
            }
        });
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 370, 30));

        PassForget.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PassForget.setForeground(new java.awt.Color(204, 0, 0));
        PassForget.setText("نسيت كلمة المرور !");
        PassForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassForgetMouseClicked(evt);
            }
        });
        getContentPane().add(PassForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 120, 20));

        Entree.setBackground(new java.awt.Color(189, 228, 253));
        Entree.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        Entree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_import_32px.png"))); // NOI18N
        Entree.setText("دخول");
        Entree.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeActionPerformed(evt);
            }
        });
        getContentPane().add(Entree, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 120, 32));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("إسم المستخدم");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 190, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("كلمة المرور ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, 40));

        jButton1.setBackground(new java.awt.Color(210, 13, 20));
        jButton1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_export_32px.png"))); // NOI18N
        jButton1.setText("خروج");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 120, 32));

        Passwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Passwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswdKeyPressed(evt);
            }
        });
        getContentPane().add(Passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 370, 30));

        ContactMe.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ContactMe.setText("Contacter le développeur");
        ContactMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactMeMouseClicked(evt);
            }
        });
        getContentPane().add(ContactMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        BackGround.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/LoginBG 900+540.png"))); // NOI18N
        BackGround.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        BackGround.setMaximumSize(new java.awt.Dimension(900, 540));
        BackGround.setMinimumSize(new java.awt.Dimension(900, 540));
        BackGround.setPreferredSize(new java.awt.Dimension(900, 540));
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeActionPerformed
        char[] pass = Passwd.getPassword();
        String Pswd = "";
        for (int i = 0; i < pass.length; i++) {
            Pswd = Pswd + pass[i];
        }
        String query = "select * from User where nomutilisateur=? and password=? ";
        try {

            if (Root.RtUspn.equals(UserName.getText()) && Root.RtPwd.equals(Pswd)) {
                Root RootStart = new Root();
                RootStart.setVisible(true);
            } else {
                PstLog = ConnctDB.prepareStatement(query);
                PstLog.setString(1, UserName.getText());
                PstLog.setString(2, Pswd);
                ResSetLog = PstLog.executeQuery();
                if (ResSetLog.next()) {
                    String AdminOuNon = ResSetLog.getString("IsAdmin");
                    if (AdminOuNon.equals("true")) {//IsAdmin
                        CEMGS.StartAdmin();
                        dispose();
                    } else {
                        if (AdminOuNon.equals("false")) {
                            CEMGS.StartHome();
                            dispose();
                        } else {
                        }
                    }
                    ResSetLog.close();
                    PstLog.close();
                } else {
                    JOptionPane.showMessageDialog(this, " Mot de Pass ou le nom utilisateur Faux !");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EntreeActionPerformed

    private void UserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameMouseClicked
        UserName.setText("");
    }//GEN-LAST:event_UserNameMouseClicked

    private void PassForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassForgetMouseClicked
        JOptionPane.showMessageDialog(this, "Contacter l'administration");
    }//GEN-LAST:event_PassForgetMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContactMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMeMouseClicked
        Contact c = new Contact();
        c.setVisible(true);
        //JOptionPane.showMessageDialog(this, "Ferhat Hamza \nMobile. 06 6942 9363 \nEmail. FerhatHamza4@gmail.com ");
    }//GEN-LAST:event_ContactMeMouseClicked

    private void PasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            char[] pass = Passwd.getPassword();
            String Pswd = "";
            for (int i = 0; i < pass.length; i++) {
                Pswd = Pswd + pass[i];
            }
            String query = "select * from User where nomutilisateur=? and password=? ";
            try {

                if (Root.RtUspn.equals(UserName.getText()) && Root.RtPwd.equals(Pswd)) {
                    Root RootStart = new Root();
                    RootStart.setVisible(true);
                } else {
                    PstLog = ConnctDB.prepareStatement(query);
                    PstLog.setString(1, UserName.getText());
                    PstLog.setString(2, Pswd);
                    ResSetLog = PstLog.executeQuery();
                    if (ResSetLog.next()) {
                        String AdminOuNon = ResSetLog.getString("IsAdmin");
                        if (AdminOuNon.equals("true")) {//IsAdmin
                            CEMGS.StartAdmin();
                            dispose();
                        } else {
                            if (AdminOuNon.equals("false")) {
                                CEMGS.StartHome();
                                dispose();
                            } else {
                            }
                        }
                        ResSetLog.close();
                        PstLog.close();
                    } else {
                        JOptionPane.showMessageDialog(this, " Mot de Pass ou le nom utilisateur Faux !");
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_PasswdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel ContactMe;
    private javax.swing.JButton Entree;
    private javax.swing.JLabel PassForget;
    private javax.swing.JPasswordField Passwd;
    private javax.swing.JTextField UserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
