/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemgs;

import java.sql.*;
import cemgs.Home;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ZaHi
 */
public class Misajour extends javax.swing.JFrame {

    Connection Conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public Misajour() {
        initComponents();
        Conn = Connect.connect();
        SetDesigComboFromDb();
        TableFilMis();
    }
    
    public void TableFilMis(){
        String SqlTab = "Select id,nom,quntity,reference,Designation,source, nbrBon,date from Stock";
        try{
            pst = Conn.prepareStatement(SqlTab);
            rs = pst.executeQuery();
            MisTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            e.getMessage();
        }
        
        MisTable.getColumnModel().getColumn(0).setMinWidth(40);
        MisTable.getColumnModel().getColumn(0).setMaxWidth(40);
        MisTable.getColumnModel().getColumn(0).setHeaderValue("Id");
        
        MisTable.getColumnModel().getColumn(1).setMinWidth(120);
        MisTable.getColumnModel().getColumn(1).setMaxWidth(140);
        MisTable.getColumnModel().getColumn(1).setHeaderValue("Nom");
        
        MisTable.getColumnModel().getColumn(2).setMinWidth(50);
        MisTable.getColumnModel().getColumn(2).setMaxWidth(70);
        MisTable.getColumnModel().getColumn(2).setHeaderValue("Qentiteé");
        
        MisTable.getColumnModel().getColumn(3).setMinWidth(50);
        MisTable.getColumnModel().getColumn(3).setMaxWidth(70);
        MisTable.getColumnModel().getColumn(3).setHeaderValue("Référence");
        
        MisTable.getColumnModel().getColumn(4).setMinWidth(100);
        MisTable.getColumnModel().getColumn(4).setMaxWidth(120);
        MisTable.getColumnModel().getColumn(4).setHeaderValue("Designation");
        
        MisTable.getColumnModel().getColumn(5).setMinWidth(120);
        MisTable.getColumnModel().getColumn(5).setMaxWidth(150);
        MisTable.getColumnModel().getColumn(5).setHeaderValue("Source");
        
        MisTable.getColumnModel().getColumn(6).setMinWidth(65);
        MisTable.getColumnModel().getColumn(6).setMaxWidth(80);
        MisTable.getColumnModel().getColumn(6).setHeaderValue("N° de Bon");
        
        MisTable.getColumnModel().getColumn(7).setMinWidth(65);
        MisTable.getColumnModel().getColumn(7).setMaxWidth(85);
        MisTable.getColumnModel().getColumn(7).setHeaderValue("Date");
        
    }
    
    
     public void SetDesigComboFromDb() {

        try {
            String sql = "SELECT nom ,reference FROM Designation";
            pst = Conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String Ref = rs.getString("reference");
                String Item = rs.getString("nom");
                MisJStockDesigCombo.addItem(Item);

                String query = "UPDATE Stock  SET  reference = '" + Ref + "' WHERE Designation = '" + Item + "' ";
                pst = Conn.prepareStatement(query);
                pst.executeUpdate();
            }
            MisJStockDesig.setText((String) MisJStockDesigCombo.getSelectedItem());
        } catch (Exception e) {
        }
        try {

        } catch (Exception e) {

        }
    }
    
     public void Setreference(String Aref, String DesigStockDBVar, int id) {

        try {
            String sql = "SELECT nom ,reference FROM Designation";
            pst = Conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String Ref = rs.getString("reference");
                if (rs.getString("nom").equals(DesigStockDBVar)) {
                    String query = "UPDATE Stock  SET  reference = '" + Ref + "." + Aref + "' WHERE Designation = '" + DesigStockDBVar + "'and id = '" + id + "'";
                    pst = Conn.prepareStatement(query);
                    pst.executeUpdate();
                }
            }
        } catch (Exception e) {
        }
        try {

        } catch (Exception e) {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MisTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MisJStockNom = new javax.swing.JTextField();
        MisJStockRef = new javax.swing.JTextField();
        MisJStockDesig = new javax.swing.JTextField();
        MisJStockNbrBon = new javax.swing.JTextField();
        MisJStockSource = new javax.swing.JTextField();
        MisJStockQuntite = new javax.swing.JTextField();
        MisJStock = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MisJStockId = new javax.swing.JTextField();
        MisJStockDesigCombo = new javax.swing.JComboBox<>();
        MisJStockDateCh = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        MisJExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Mis à Jour");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 169, 213));

        MisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Entree", "Sortie", "N° Bon", "Provenance", "Destination", "Date"
            }
        ));
        MisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MisTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MisTable);
        if (MisTable.getColumnModel().getColumnCount() > 0) {
            MisTable.getColumnModel().getColumn(1).setMinWidth(63);
            MisTable.getColumnModel().getColumn(1).setPreferredWidth(63);
            MisTable.getColumnModel().getColumn(1).setMaxWidth(63);
            MisTable.getColumnModel().getColumn(2).setMinWidth(63);
            MisTable.getColumnModel().getColumn(2).setPreferredWidth(63);
            MisTable.getColumnModel().getColumn(2).setMaxWidth(63);
            MisTable.getColumnModel().getColumn(3).setMinWidth(74);
            MisTable.getColumnModel().getColumn(3).setPreferredWidth(74);
            MisTable.getColumnModel().getColumn(3).setMaxWidth(74);
            MisTable.getColumnModel().getColumn(6).setMinWidth(70);
            MisTable.getColumnModel().getColumn(6).setPreferredWidth(70);
            MisTable.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 630, 400));

        jPanel2.setBackground(new java.awt.Color(1, 169, 213));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Reference :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Designation :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("N° Bon :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Source :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quntite:");

        MisJStockNbrBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisJStockNbrBonActionPerformed(evt);
            }
        });

        MisJStock.setBackground(new java.awt.Color(56, 195, 164));
        MisJStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_synchronize_filled_32px_1.png"))); // NOI18N
        MisJStock.setText("Mis à Jour");
        MisJStock.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MisJStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisJStockActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Date :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Id :");

        MisJStockId.setEditable(false);
        MisJStockId.setText("0");

        MisJStockDesigCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisJStockDesigComboActionPerformed(evt);
            }
        });

        MisJStockDateCh.setBackground(new java.awt.Color(1, 169, 213));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MisJStockQuntite, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MisJStockDateCh, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2))))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MisJStockNom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MisJStockNbrBon)
                    .addComponent(MisJStockSource)
                    .addComponent(MisJStockId)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MisJStockDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MisJStockDesigCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MisJStockRef)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MisJStock))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MisJStockId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MisJStockNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MisJStockRef, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MisJStockDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(MisJStockDesigCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MisJStockNbrBon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MisJStockSource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MisJStockQuntite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(MisJStockDateCh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MisJStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 290, 300));

        jPanel3.setBackground(new java.awt.Color(189, 181, 168));

        MisJExit.setBackground(new java.awt.Color(210, 13, 20));
        MisJExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_shutdown_filled_32px.png"))); // NOI18N
        MisJExit.setText("Exit");
        MisJExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        MisJExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisJExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(MisJExit)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(MisJExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/Misajour.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MisJStockNbrBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisJStockNbrBonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MisJStockNbrBonActionPerformed

    private void MisJExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisJExitActionPerformed
        dispose();
    }//GEN-LAST:event_MisJExitActionPerformed

    private void MisJStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisJStockActionPerformed
        int id = Integer.parseInt(MisJStockId.getText());
        String MisJStockDate = ((JTextField) MisJStockDateCh.getDateEditor().getUiComponent()).getText();
        
       if (MisJStockNom.getText().equals("") || MisJStockRef.getText().equals("") || MisJStockDesig.getText().equals("") || MisJStockNbrBon.getText().equals("") || MisJStockSource.getText().equals("") || MisJStockQuntite.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "le nom et référence , Designation, N° de Bon, date, source , quntity ,est une obligation que vous devez remplir");
        } else {
            try {
                String query = "UPDATE Stock "
                        + " SET  nom = '" + MisJStockNom.getText() + "',quntity = '" + MisJStockQuntite.getText() + "' "
                        + ",reference = '" + MisJStockRef.getText() + "' ,source = '" + MisJStockSource.getText() + "' ,nbrBon = '" + MisJStockNbrBon.getText() + "'"
                        + ",date = '" + MisJStockDate + "' ,Designation = '" + MisJStockDesig.getText() + "' "
                        + " WHERE id = '" + id + "' ";
                pst = Conn.prepareStatement(query);
                pst.executeUpdate();
                
                Setreference(MisJStockRef.getText() ,MisJStockDesig.getText(),id);
                MisJStockId.setText("0");
                MisJStockNom.setText("");
                MisJStockRef.setText("");
                MisJStockDesig.setText("");
                MisJStockNbrBon.setText("");
                MisJStockSource.setText("");
                MisJStockQuntite.setText("");
            } catch (Exception e) {

            }
            TableFilMis();
        }
        

    }//GEN-LAST:event_MisJStockActionPerformed

    private void MisJStockDesigComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisJStockDesigComboActionPerformed
        MisJStockDesig.setText((String) MisJStockDesigCombo.getSelectedItem());
    }//GEN-LAST:event_MisJStockDesigComboActionPerformed

    private void MisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MisTableMouseClicked
        int Ligne = MisTable.getSelectedRow();
        String id = MisTable.getModel().getValueAt(Ligne, 0).toString();
        String nom = MisTable.getModel().getValueAt(Ligne, 1).toString();
        String quntity = MisTable.getModel().getValueAt(Ligne, 2).toString();
        String reference = MisTable.getModel().getValueAt(Ligne, 3).toString();
        String Designation = MisTable.getModel().getValueAt(Ligne, 4).toString();
        String source = MisTable.getModel().getValueAt(Ligne, 5).toString();
        String nbrBon = MisTable.getModel().getValueAt(Ligne, 6).toString();
        
        MisJStockId.setText(id);
        MisJStockNom.setText(nom);
        MisJStockDesig.setText(Designation);
        MisJStockRef.setText(reference);
        MisJStockNbrBon.setText(nbrBon);
        MisJStockSource.setText(source);
        MisJStockQuntite.setText(quntity);
    }//GEN-LAST:event_MisTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Misajour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Misajour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Misajour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Misajour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Misajour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MisJExit;
    private javax.swing.JButton MisJStock;
    private com.toedter.calendar.JDateChooser MisJStockDateCh;
    private javax.swing.JTextField MisJStockDesig;
    private javax.swing.JComboBox<String> MisJStockDesigCombo;
    private javax.swing.JTextField MisJStockId;
    private javax.swing.JTextField MisJStockNbrBon;
    private javax.swing.JTextField MisJStockNom;
    private javax.swing.JTextField MisJStockQuntite;
    private javax.swing.JTextField MisJStockRef;
    private javax.swing.JTextField MisJStockSource;
    private javax.swing.JTable MisTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
