/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemgs;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ZaHi
 */
public class MisDesignation extends javax.swing.JFrame {

    Connection Conn = null;
    PreparedStatement Pst = null;
    ResultSet rs = null;
    
    public MisDesignation() {
        initComponents();
        Conn = Connect.connect();
        TableFilHome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void TableFilHome() {
     String SqlTab = "Select id,nom,reference,zone from Designation";
        try {
            Pst = Conn.prepareStatement(SqlTab);
            rs = Pst.executeQuery();
            MisDesigTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.getMessage();
        }

        MisDesigTable.getColumnModel().getColumn(0).setMinWidth(40);
        MisDesigTable.getColumnModel().getColumn(0).setMaxWidth(40);
        MisDesigTable.getColumnModel().getColumn(0).setHeaderValue("Id");

        MisDesigTable.getColumnModel().getColumn(1).setMinWidth(150);
        MisDesigTable.getColumnModel().getColumn(1).setMaxWidth(150);
        MisDesigTable.getColumnModel().getColumn(1).setHeaderValue("Nom");

        MisDesigTable.getColumnModel().getColumn(2).setMinWidth(90);
        MisDesigTable.getColumnModel().getColumn(2).setMaxWidth(90);
        MisDesigTable.getColumnModel().getColumn(2).setHeaderValue("Référence");
        
        MisDesigTable.getColumnModel().getColumn(3).setMinWidth(100);
        MisDesigTable.getColumnModel().getColumn(3).setMaxWidth(125);
        MisDesigTable.getColumnModel().getColumn(3).setHeaderValue("Zone");


    }

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MisBnt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DesigIDinter = new javax.swing.JTextField();
        DesigNomintr = new javax.swing.JTextField();
        DesigRefintr = new javax.swing.JTextField();
        DesigZoneIntr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MisDesigTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Designation Mis à jour");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 169, 203));

        MisBnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_synchronize_filled_32px_1.png"))); // NOI18N
        MisBnt.setText("Mis à Jour");
        MisBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisBntActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :");

        jLabel2.setText("Nom :");

        jLabel3.setText("Référence :");

        DesigIDinter.setEditable(false);
        DesigIDinter.setText("0");

        jLabel5.setText("Zone :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MisBnt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DesigNomintr)
                            .addComponent(DesigIDinter, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DesigZoneIntr, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(DesigRefintr))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DesigIDinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DesigNomintr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesigRefintr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesigZoneIntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addComponent(MisBnt)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 290, 270));

        MisDesigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nom", "Reference", "Zone"
            }
        ));
        MisDesigTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MisDesigTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MisDesigTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 410, 380));

        jButton1.setBackground(new java.awt.Color(197, 82, 82));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_shutdown_filled_32px.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/MisAjour mini.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MisBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisBntActionPerformed
        String DesigIDVar = DesigIDinter.getText();
        String DesigNomVar = DesigNomintr.getText();
        String DesigRefVar = DesigRefintr.getText();
        String DesigZoneVar = DesigZoneIntr.getText();
        int idg = Integer.parseInt(DesigIDVar);
        if (DesigIDVar.equals("0")) {
            JOptionPane.showMessageDialog(this, "S'il vous plaît choisir un stock de la table");
        }
        String query = "UPDATE Designation "
                + " SET nom = '" + DesigNomVar + "',reference = '" + DesigRefVar + "' ,zone = '" + DesigZoneVar + "' "
                + "where id = '" + idg + "'";

        try {
            Pst = Conn.prepareStatement(query);
            Pst.executeUpdate();
            Pst.close();
        } catch (Exception e) {
        }
        DesigIDinter.setText("0");
        DesigNomintr.setText("");
        DesigRefintr.setText("");
        DesigZoneIntr.setText("");
        TableFilHome();
    }//GEN-LAST:event_MisBntActionPerformed

    private void MisDesigTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MisDesigTableMouseClicked
        int Ligne = MisDesigTable.getSelectedRow();
        String id = MisDesigTable.getModel().getValueAt(Ligne, 0).toString();
        String nom = MisDesigTable.getModel().getValueAt(Ligne, 1).toString();
        String reference = MisDesigTable.getModel().getValueAt(Ligne, 2).toString();
        String Zone = MisDesigTable.getModel().getValueAt(Ligne, 3).toString();
        
        DesigIDinter.setText(id);
        DesigNomintr.setText(nom);
        DesigRefintr.setText(reference);
        DesigZoneIntr.setText(Zone);
        
    }//GEN-LAST:event_MisDesigTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisDesignation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DesigIDinter;
    private javax.swing.JTextField DesigNomintr;
    private javax.swing.JTextField DesigRefintr;
    private javax.swing.JTextField DesigZoneIntr;
    private javax.swing.JButton MisBnt;
    private javax.swing.JTable MisDesigTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
