/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemgs;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ZaHi
 */
public class Supprime extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Supprime() {
        initComponents();
        conn = Connect.connect();
        TableFilSupp();

    }
    public void TableFilSupp(){
        String SqlTab = "Select id,nom,quntity,reference,Designation, nbrBon,date from Stock";
        try{
            pst = conn.prepareStatement(SqlTab);
            rs = pst.executeQuery();
            SuppTap.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            e.getMessage();
        }
        SuppTap.getColumnModel().getColumn(0).setMinWidth(20);
        SuppTap.getColumnModel().getColumn(0).setMaxWidth(40);
        SuppTap.getColumnModel().getColumn(0).setHeaderValue("Id");
        
        SuppTap.getColumnModel().getColumn(1).setMinWidth(120);
        SuppTap.getColumnModel().getColumn(1).setMaxWidth(140);
        SuppTap.getColumnModel().getColumn(1).setHeaderValue("Nom");
        
        SuppTap.getColumnModel().getColumn(2).setMinWidth(50);
        SuppTap.getColumnModel().getColumn(2).setMaxWidth(70);
        SuppTap.getColumnModel().getColumn(2).setHeaderValue("Qentiteé");
        
        SuppTap.getColumnModel().getColumn(3).setMinWidth(50);
        SuppTap.getColumnModel().getColumn(3).setMaxWidth(70);
        SuppTap.getColumnModel().getColumn(3).setHeaderValue("Référence");
        
        SuppTap.getColumnModel().getColumn(4).setMinWidth(120);
        SuppTap.getColumnModel().getColumn(4).setMaxWidth(140);
        SuppTap.getColumnModel().getColumn(4).setHeaderValue("Designation");
        
        SuppTap.getColumnModel().getColumn(5).setMinWidth(60);
        SuppTap.getColumnModel().getColumn(5).setMaxWidth(80);
        SuppTap.getColumnModel().getColumn(5).setHeaderValue("N° de Bon");
        
        SuppTap.getColumnModel().getColumn(6).setMinWidth(65);
        SuppTap.getColumnModel().getColumn(6).setMaxWidth(85);
        SuppTap.getColumnModel().getColumn(6).setHeaderValue("Date");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuppTap = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SuppStockNom = new javax.swing.JTextField();
        SuppStockRef = new javax.swing.JTextField();
        SuppStockQuntite = new javax.swing.JTextField();
        SupprimeDB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SuppStocId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ExitSupprimeIntr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supprimer Stock");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 169, 213));

        SuppTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Entree", "Sortie", "N° Bon", "Provenance", "Destination", "Date"
            }
        ));
        SuppTap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuppTapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SuppTap);
        if (SuppTap.getColumnModel().getColumnCount() > 0) {
            SuppTap.getColumnModel().getColumn(1).setMinWidth(63);
            SuppTap.getColumnModel().getColumn(1).setPreferredWidth(63);
            SuppTap.getColumnModel().getColumn(1).setMaxWidth(63);
            SuppTap.getColumnModel().getColumn(2).setMinWidth(63);
            SuppTap.getColumnModel().getColumn(2).setPreferredWidth(63);
            SuppTap.getColumnModel().getColumn(2).setMaxWidth(63);
            SuppTap.getColumnModel().getColumn(3).setMinWidth(74);
            SuppTap.getColumnModel().getColumn(3).setPreferredWidth(74);
            SuppTap.getColumnModel().getColumn(3).setMaxWidth(74);
            SuppTap.getColumnModel().getColumn(6).setMinWidth(70);
            SuppTap.getColumnModel().getColumn(6).setPreferredWidth(70);
            SuppTap.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 630, 400));

        jPanel2.setBackground(new java.awt.Color(1, 169, 213));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Reference :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quntite :");

        SuppStockNom.setEditable(false);

        SuppStockRef.setEditable(false);

        SuppStockQuntite.setEditable(false);

        SupprimeDB.setBackground(new java.awt.Color(197, 82, 82));
        SupprimeDB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupprimeDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_clear_shopping_cart_filled_32px_1.png"))); // NOI18N
        SupprimeDB.setText("Supprime");
        SupprimeDB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SupprimeDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimeDBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Id :");

        SuppStocId.setEditable(false);
        SuppStocId.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupprimeDB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SuppStockQuntite, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SuppStockNom, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(SuppStockRef)
                            .addComponent(SuppStocId))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SuppStocId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuppStockNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuppStockRef, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SuppStockQuntite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(SupprimeDB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 290, 270));

        jPanel3.setBackground(new java.awt.Color(208, 209, 207));

        ExitSupprimeIntr.setBackground(new java.awt.Color(197, 82, 82));
        ExitSupprimeIntr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExitSupprimeIntr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_shutdown_filled_32px.png"))); // NOI18N
        ExitSupprimeIntr.setText("Exit");
        ExitSupprimeIntr.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ExitSupprimeIntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSupprimeIntrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitSupprimeIntr))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ExitSupprimeIntr)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/supp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimeDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimeDBActionPerformed
        String SuppStockIdVar = SuppStocId.getText();
        String SuppStockNomVar = SuppStockNom.getText();
        String SuppStockRefVar = SuppStockRef.getText();
        String SuppStockQuntiteVar = SuppStockQuntite.getText();
        int x = Integer.parseInt(SuppStockIdVar);

        if (SuppStockIdVar.equals("0")) {
            JOptionPane.showMessageDialog(this, "S'il vous plaît choisir un Stock de la table");
        } else {
            try {
                String sql = "DELETE FROM Stock WHERE id = '" + x + "'";
                pst = conn.prepareStatement(sql);
                pst.execute();
            } catch (Exception e) {
            }
        }
        TableFilSupp();
        SuppStockQuntite.setText("");
        SuppStockRef.setText("");
        SuppStockNom.setText("");
        SuppStocId.setText("0");
        

    }//GEN-LAST:event_SupprimeDBActionPerformed

    private void ExitSupprimeIntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSupprimeIntrActionPerformed
        dispose();
        
    }//GEN-LAST:event_ExitSupprimeIntrActionPerformed

    private void SuppTapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppTapMouseClicked
        int Ligne = SuppTap.getSelectedRow();
        String id = SuppTap.getModel().getValueAt(Ligne, 0).toString();
        String nom = SuppTap.getModel().getValueAt(Ligne, 1).toString();
        String quntity = SuppTap.getModel().getValueAt(Ligne, 2).toString();
        String reference = SuppTap.getModel().getValueAt(Ligne, 3).toString();
        String Designation = SuppTap.getModel().getValueAt(Ligne, 4).toString();
        String source = SuppTap.getModel().getValueAt(Ligne, 5).toString();
        String nbrBon = SuppTap.getModel().getValueAt(Ligne, 6).toString();
        
        SuppStocId.setText(id);
        SuppStockNom.setText(nom);
        SuppStockRef.setText(reference);
        SuppStockQuntite.setText(quntity);
    }//GEN-LAST:event_SuppTapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supprime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitSupprimeIntr;
    private javax.swing.JTextField SuppStocId;
    private javax.swing.JTextField SuppStockNom;
    private javax.swing.JTextField SuppStockQuntite;
    private javax.swing.JTextField SuppStockRef;
    private javax.swing.JTable SuppTap;
    private javax.swing.JButton SupprimeDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
