/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemgs;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ZaHi
 */
public class UserGestion extends javax.swing.JFrame {

    Connection Conn = null;
    PreparedStatement pst = null;

    public UserGestion() {
        initComponents();
        Conn = Connect.connect();
        TableFilUser();
    }

    public void TableFilUser() {
        String SqlTab = "Select Id,NomPrenom ,nomutilisateur,password from user";

        try {
            pst = Conn.prepareStatement(SqlTab);
            ResultSet rs = pst.executeQuery();
            UserTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.getMessage();
        }
        UserTable.getColumnModel().getColumn(0).setMinWidth(20);
        UserTable.getColumnModel().getColumn(0).setMaxWidth(40);
        UserTable.getColumnModel().getColumn(0).setHeaderValue("Id");
        UserTable.getColumnModel().getColumn(1).setMinWidth(120);
        UserTable.getColumnModel().getColumn(1).setMaxWidth(150);
        UserTable.getColumnModel().getColumn(1).setHeaderValue("Nom et Prenom");
        UserTable.getColumnModel().getColumn(2).setMinWidth(100);
        UserTable.getColumnModel().getColumn(2).setHeaderValue("Nom Utilisateur");
        UserTable.getColumnModel().getColumn(3).setMinWidth(80);
        UserTable.getColumnModel().getColumn(3).setHeaderValue("Mot de Pass");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UgestAddUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UgestAddNomPrenom = new javax.swing.JTextField();
        UgestionAddDB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UgestAddMotPass = new javax.swing.JTextField();
        DeltUser = new javax.swing.JButton();
        UgestionMisDB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Userid = new javax.swing.JTextField();
        isMe = new javax.swing.JComboBox<>();
        Actual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        ExitUserGestion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion d'utilisateur");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 169, 213));

        jLabel2.setText("Nom Utilisateur :");

        jLabel4.setText("Nom et Prenom :");

        UgestionAddDB.setBackground(new java.awt.Color(56, 195, 164));
        UgestionAddDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_add_user_group_filled_32px.png"))); // NOI18N
        UgestionAddDB.setText("Ajouter");
        UgestionAddDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UgestionAddDBActionPerformed(evt);
            }
        });

        jLabel3.setText("Mot de Pass :");

        DeltUser.setBackground(new java.awt.Color(197, 82, 82));
        DeltUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_remove_user_male_30px.png"))); // NOI18N
        DeltUser.setText("Supprimer");
        DeltUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeltUserActionPerformed(evt);
            }
        });

        UgestionMisDB.setBackground(new java.awt.Color(56, 195, 164));
        UgestionMisDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_checked_user_filled_32px.png"))); // NOI18N
        UgestionMisDB.setText("Mis à Jour");
        UgestionMisDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UgestionMisDBActionPerformed(evt);
            }
        });

        jLabel8.setText("Id :");

        Userid.setEditable(false);
        Userid.setText("0");
        Userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseridActionPerformed(evt);
            }
        });

        isMe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Semple Utlisateur" }));

        Actual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_synchronize_filled_32px_1.png"))); // NOI18N
        Actual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Actual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(DeltUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UgestionMisDB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(UgestAddMotPass)
                                        .addGap(67, 67, 67))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(UgestionAddDB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Userid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(UgestAddUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UgestAddNomPrenom)
                                    .addComponent(isMe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Userid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UgestAddNomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UgestAddUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UgestionAddDB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(UgestAddMotPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeltUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UgestionMisDB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, 220));

        jPanel3.setBackground(new java.awt.Color(1, 169, 213));

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Utilisateur", "Mot de Pass", "Nom et Prenom"
            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);
        if (UserTable.getColumnModel().getColumnCount() > 0) {
            UserTable.getColumnModel().getColumn(0).setMinWidth(80);
            UserTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            UserTable.getColumnModel().getColumn(0).setMaxWidth(80);
            UserTable.getColumnModel().getColumn(1).setMinWidth(100);
            UserTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            UserTable.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 360, 300));

        ExitUserGestion.setBackground(new java.awt.Color(197, 82, 82));
        ExitUserGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/icons8_shutdown_filled_32px.png"))); // NOI18N
        ExitUserGestion.setText("Exit");
        ExitUserGestion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ExitUserGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitUserGestionActionPerformed(evt);
            }
        });
        getContentPane().add(ExitUserGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemgs/Image/UserGetion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UgestionAddDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UgestionAddDBActionPerformed
        String UgestAddUserNameVar = UgestAddUserName.getText();
        String UgestAddMotPassVar = UgestAddMotPass.getText();
        String UgestAddNomPrenomVar = UgestAddNomPrenom.getText();
        String isAdminvar = (String) isMe.getSelectedItem(), BolAdmin = "";
        if (isAdminvar.equals("Admin")) {//Semple Utlisateur
            BolAdmin = "true";
        } else {
            BolAdmin = "false";
        }
        if (UgestAddUserNameVar.equals("") || UgestAddMotPassVar.equals("") || UgestAddNomPrenomVar.equals("")) {
            JOptionPane.showMessageDialog(this, "le Nom et Prenom et Nom Utilisateur ,Mot de Pass ,est une obligation que vous devez remplir");
        } else {
            try {
                String Sql = "insert into user (NomPrenom , nomutilisateur, password, IsAdmin) values ('" + UgestAddNomPrenomVar + "','" + UgestAddUserNameVar + "'"
                        + ",'" + UgestAddMotPassVar + "','" + BolAdmin + "')";
                pst = Conn.prepareStatement(Sql);
                pst.execute();
            } catch (Exception e) {
            }
        }
        TableFilUser();
        UgestAddUserName.setText("");
        UgestAddMotPass.setText("");
        UgestAddNomPrenom.setText("");
        Userid.setText("0");
    }//GEN-LAST:event_UgestionAddDBActionPerformed

    private void ExitUserGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitUserGestionActionPerformed
        CEMGS.StartAdmin();
        dispose();
    }//GEN-LAST:event_ExitUserGestionActionPerformed

    private void UgestionMisDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UgestionMisDBActionPerformed
        String UgestAddUserNameVar = UgestAddUserName.getText();
        UgestAddUserName.setText("");
        String UgestAddMotPassVar = UgestAddMotPass.getText();
        UgestAddMotPass.setText("");
        String UgestAddNomPrenomVar = UgestAddNomPrenom.getText();
        UgestAddNomPrenom.setText("");
        String UseridVar = Userid.getText();
        String isAdminvar = (String) isMe.getSelectedItem(), BolAdmin = "";
        if (UseridVar.equals("1")) {
            JOptionPane.showMessageDialog(this, "Vous ne pouvez pas mettre à jour les informations de cet utilisateur");
        } else {
            if (isAdminvar.equals("Admin")) {//Semple Utlisateur
                BolAdmin = "true";
            } else {
                BolAdmin = "false";
            }
            if (UgestAddUserNameVar.equals("") || UgestAddMotPassVar.equals("") || UgestAddNomPrenomVar.equals("")) {
                JOptionPane.showMessageDialog(this, "le Nom et Prenom et Nom Utilisateur ,Mot de Pass ,est une obligation que vous devez remplir");
            } else {
                try {
                    String query = "UPDATE user "
                            + " SET  nomutilisateur = '" + UgestAddUserNameVar + "',password = '" + UgestAddMotPassVar + "' ,NomPrenom = '" + UgestAddNomPrenomVar + "' ,IsAdmin = '" + BolAdmin + "' "
                            + " WHERE Id = '" + UseridVar + "'";
                    pst = Conn.prepareStatement(query);
                    pst.executeUpdate();
                } catch (Exception e) {

                }
            }
            TableFilUser();
            Userid.setText("0");
        }


    }//GEN-LAST:event_UgestionMisDBActionPerformed

    private void DeltUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeltUserActionPerformed
        String UgestAddUserNameVar = UgestAddUserName.getText();
        String UgestAddMotPassVa = UgestAddMotPass.getText();
        String UgestAddNomPrenomVar = UgestAddNomPrenom.getText();
        String UseridVar = Userid.getText();
        int x = Integer.parseInt(UseridVar);
        if (UseridVar.equals("0")) {
            JOptionPane.showMessageDialog(this, "S'il vous plaît choisir un User de la table");
        } else {
            if (UseridVar.equals("1") || UseridVar.equals("2")) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner un autre utilisateur dans le tableau. Vous ne pouvez pas supprimer cet utilisateur.");
            } else {
                try {
                    String sql = "DELETE FROM user WHERE Id = '" + x + "'";
                    pst = Conn.prepareStatement(sql);
                    pst.execute();
                } catch (Exception e) {
                }
            }

        }
        TableFilUser();
        UgestAddNomPrenom.setText("");
        UgestAddUserName.setText("");
        UgestAddMotPass.setText("");
        Userid.setText("0");
    }//GEN-LAST:event_DeltUserActionPerformed

    private void UseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UseridActionPerformed

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        int Ligne = UserTable.getSelectedRow();
        String id = UserTable.getModel().getValueAt(Ligne, 0).toString();
        String NomPrenom = UserTable.getModel().getValueAt(Ligne, 1).toString();
        String UserName = UserTable.getModel().getValueAt(Ligne, 2).toString();
        String MotPass = UserTable.getModel().getValueAt(Ligne, 3).toString();
        Userid.setText(id);
        UgestAddNomPrenom.setText(NomPrenom);
        UgestAddUserName.setText(UserName);
        UgestAddMotPass.setText(MotPass);

    }//GEN-LAST:event_UserTableMouseClicked

    private void ActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualMouseClicked
        UgestAddNomPrenom.setText("");
        UgestAddUserName.setText("");
        UgestAddMotPass.setText("");
        Userid.setText("0");
    }//GEN-LAST:event_ActualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actual;
    private javax.swing.JButton DeltUser;
    private javax.swing.JButton ExitUserGestion;
    private javax.swing.JTextField UgestAddMotPass;
    private javax.swing.JTextField UgestAddNomPrenom;
    private javax.swing.JTextField UgestAddUserName;
    private javax.swing.JButton UgestionAddDB;
    private javax.swing.JButton UgestionMisDB;
    private javax.swing.JTable UserTable;
    private javax.swing.JTextField Userid;
    private javax.swing.JComboBox<String> isMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
